#!/bin/sh

usage () {
    echo "\niCryptoNode Configuration Program"
    echo "Usage: icn_configure [monero|vertcoin]\n"
    exit 0
}

print_info () {
    echo "\n====> $1\n"
}

if [ -z "$1" ]; then
    usage

elif [ "$1" = "monero" ]; then
    print_info "Configuring a monero node"

elif [ "$1" = "vertcoin" ]; then
    print_info "Configuring a vertcoin node"

else
    print_info "Error: unknown node type '$1'"
    usage
fi

ROOT_DIR=/var/www/html/icryptonode

print_info "Installing required packages"
sudo apt-get update
sudo apt-get --assume-yes install ufw openvpn unzip lighttpd cmake dh-autoreconf git \
    lua5.1 liblua5.1-0-dev php7.0-fpm php7.0-cgi php-pear php7.0-dev \
    libgpgme11 libgpgme-dev dnsutils


print_info "Installing PHP extensions"
sudo pecl install gnupg

print_info "Creating icryptonode daemon dirs"
sudo mkdir /etc/icryptonode
sudo mkdir /etc/icryptonode/daemon
sudo mkdir /etc/icryptonode/blockchain
sudo cp ./fix_folders.sh /etc/icryptonode

print_info "Importing iCryptoNode official PGP public key"
sudo mkdir /etc/icryptonode/.gnupg
sudo gpg --import --homedir /etc/icryptonode/.gnupg ./iCryptoNode_Official_PGP_Key.txt 

print_info "Changing ownership to www-data user"
sudo chown -R www-data:www-data /etc/icryptonode

print_info "Enabling lighttpd extensions"
sudo lighty-enable-mod fastcgi 
sudo lighty-enable-mod fastcgi-php

print_info "Replacing lighttpd config"
sudo cp ./lighttpd_config /etc/lighttpd/lighttpd.conf 

sudo service lighttpd force-reload

print_info "Moving iCryptoNode web software into place"
sudo cp -R ../icryptonode $ROOT_DIR

print_info "Creating VPN auth file"
touch $ROOT_DIR/vpn/auth
$ROOT_DIR/vpn/commands/change_pia_auth REPLACE_ME nothing

sudo chown -R www-data:www-data $ROOT_DIR

sudo ufw allow 22
sudo ufw allow 80

if [ "$1" = "monero" ]; then
    print_info "Opening up monero daemon ports"

    sudo ufw allow 18080
    sudo ufw allow 18081

elif [ "$1" = "vertcoin" ]; then
    print_info "Opening up vertcoin daemon ports"

    sudo ufw allow 5888
    sudo ufw allow 5889
fi

# Set crons and enable them
print_info "Creating crontab entries"
echo 'PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games' >> mycron
echo "*/1 * * * * $ROOT_DIR/cron/vpn_cron" >> mycron
echo "*/1 * * * * $ROOT_DIR/cron/daemon_cron" >> mycron
echo "*/1 * * * * $ROOT_DIR/cron/icn_update" >> mycron
sudo crontab mycron
rm mycron


print_info "Setting UCI variables"

sudo mkdir /etc/config
touch /etc/config/icryptonode
sudo uci add icryptonode info
sudo uci set icryptonode.@info[0].vpn_enabled='no'
sudo uci set icryptonode.@info[0].vpn_file='US_East.ovpn'
sudo uci set icryptonode.@info[0].daemon_version='0'
sudo uci set icryptonode.@info[0].daemon_enabled='no'
sudo uci set icryptonode.@info[0].daemon_user='icryptonode'
sudo uci set icryptonode.@info[0].daemon_pass='salmonsushi'

sudo uci set icryptonode.@info[0].is_updating='no'

if [ "$1" = "monero" ]; then
    sudo uci set icryptonode.@info[0].node_type='monero'
    sudo uci set icryptonode.@info[0].daemon_rpc_port='18081'

elif [ "$1" = "vertcoin" ]; then
    sudo uci set icryptonode.@info[0].node_type='vertcoin'
    sudo uci set icryptonode.@info[0].daemon_rpc_port='5888'
fi

sudo uci commit
sudo chown -R www-data:www-data /etc/config


echo "iCryptoNode configuration success!"